# Generated by Django 4.1.7 on 2023-07-03 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='кто создал запись'),
            preserve_default=False,
        ),
    ]
