"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^xf#g)xx=41_#d&esymb))w(phukfq9+vsl&=6=)gvem*_%g_@'
LOGGING_CONFIG = None
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# ALLOWED_HOSTS = ["127.0.0.1"]
# когда debug включен, то нужно явно указать хост на котором работает wsgi
ALLOWED_HOSTS = ['.localhost', '127.0.0.1', 'hozinventar.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',  # debug
    "captcha",
    'django_celery_results',  # celerymy
    'django_celery_beat',
    'rest_framework',
    'woman.apps.WomanConfig',
    'rest_framework.authtoken',
    'djoser',  # могут быть проблемы при миграции поэтому
    # python manage.py makemigrations authtoken ; python manage.py migrate authtoken

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware"  # debug
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates"), # добавляем директорию для переопределения стандартных шаблонов
        # например админки
            os.path.join(BASE_DIR, "static"),

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR, "static")
# STATIC_ROOT = ""
STATIC_URL = '/static/'
# STATICFILES_DIRS = ('static',)
# STATICFILES_DIRS = (STATIC_ROOT,)
# STATICFILES_FINDERS = (
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
# )

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = '/' # при авторизации можно указать куда перенаправлять после успешной авторизации тогда в классе не нужно писать функцию get_success_url()

INTERNAL_IPS = ["127.0.0.1", ]  # debug debug_toolbar


# кеширование страниц. Если не указывать, то сохранит в память. лучше импользовать только для динамиеских страниц.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache'),
    },
    'django-cache': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': "redis://127.0.0.1:6379/1",
        }
}

# CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"  # celerymy

CELERY_RESULT_BACKEND = 'django-db'  # celerymy
# CELERY_CACHE_BACKEND = 'default'  # определили в CACHES # celerymy
CELERY_CACHE_BACKEND = 'django-cache'  # определили в CACHES # celerymy
# CELERY_RESULT_BACKEND = "redis://localhost:6379"

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler" # celerymy

# https://www.django-rest-framework.org/api-guide/renderers/
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # если закоментировать эту сроку, то через браузер можно получить только гет.
        # ни какого СВАГЕРа
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # если мы хотим чтобы только авторизованные могли использовать РЕСТ
        # либо переопределить на другой класс проверки авторизации,
        # ! однако если в классе указан атрибут авторизации, то будет использовать он, а те тот что по дефолту.
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework.authentication.TokenAuthentication',  # аутантефикация по токену
            'rest_framework.authentication.BasicAuthentication',  # аутантефикация по сессии по умолчанию указаны
            'rest_framework.authentication.SessionAuthentication',  # аутантефикация по сессии
        ),
}
